//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCServiciosMusicales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> DNI { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<int> Direccion_Id { get; set; }
        public Nullable<int> TipoCliente_Id { get; set; }
        public Nullable<int> InstrumentoMusical_Id { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual InstrumentoMusical InstrumentoMusical { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
    }
}
