//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCServiciosMusicales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentoMusical
    {
        public InstrumentoMusical()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoInstrumento_Id { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Antiguedad { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual TipoInstrumento TipoInstrumento { get; set; }
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
