//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCServiciosMusicales.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiciosMusicalesEntities : DbContext
    {
        public ServiciosMusicalesEntities()
            : base("name=ServiciosMusicalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<Instrucciones> Instrucciones { get; set; }
        public DbSet<InstrumentoMusical> InstrumentoMusical { get; set; }
        public DbSet<Piezas> Piezas { get; set; }
        public DbSet<Servicio> Servicio { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<Tecnico> Tecnico { get; set; }
        public DbSet<TipoCliente> TipoCliente { get; set; }
        public DbSet<TipoInstrumento> TipoInstrumento { get; set; }
        public DbSet<TipoServicio> TipoServicio { get; set; }
    }
}
