//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCServiciosMusicales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Costo { get; set; }
        public Nullable<int> Piezas_Id { get; set; }
        public Nullable<System.DateTime> Garantia { get; set; }
        public Nullable<int> TipoServicio_Id { get; set; }
        public Nullable<int> Instrucciones_Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Estado_Id { get; set; }
        public Nullable<int> FechaProxRev { get; set; }
        public Nullable<int> Tecnico_Id { get; set; }
        public Nullable<int> InstrumentoMusical_Id { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Instrucciones Instrucciones { get; set; }
        public virtual InstrumentoMusical InstrumentoMusical { get; set; }
        public virtual Piezas Piezas { get; set; }
        public virtual Tecnico Tecnico { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
